# Generated by Django 3.0.8 on 2020-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('size', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
