# Generated by Django 3.0.8 on 2020-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikes',
            options={'verbose_name_plural': 'Bikes'},
        ),
        migrations.AddField(
            model_name='bikes',
            name='image',
            field=models.ImageField(default='defalut.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
