# Generated by Django 3.0.8 on 2020-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200801_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='description',
            field=models.TextField(default='bicklete'),
        ),
    ]
