# Generated by Django 3.0.8 on 2020-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bikes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(default='defalut.png', upload_to='media'),
        ),
    ]
