# Generated by Django 3.0.8 on 2020-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200801_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(default='defalut.png', upload_to=''),
        ),
    ]
