# Generated by Django 3.0.8 on 2020-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200801_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='color',
            field=models.CharField(default='Blu', max_length=10),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='name',
            field=models.CharField(default='Shimano', max_length=35),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='size',
            field=models.CharField(default=26, max_length=2),
        ),
    ]
