# Generated by Django 3.0.8 on 2020-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200802_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='age_category',
            field=models.CharField(default=16, max_length=15),
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_categories',
            field=models.CharField(default='BMX', max_length=50),
        ),
    ]
