# Generated by Django 3.0.8 on 2020-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200802_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='full_description',
            field=models.TextField(default='full description...'),
        ),
    ]
