# Generated by Django 3.1 on 2020-09-25 21:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_bikes_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
