# Generated by Django 3.0.7 on 2020-10-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='bike',
        ),
    ]
